### ISSUE TITLE
Browser's back button functionality is broken

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#33]
### Steps to reproduce:
 1. Load the home page
 1. Visit the `/about` page
 1. Click the browser's back button

### Expected behavior: 
Return to the home page.

### Actual behavior: 
Remained on the `/about` page.

**Comment by brookr** [comment]
During a quiz, the back button causes catastrophic loss of data.

**Comment by portermichael** [comment]
Thanks for the feedback. Issue is fixed.

https://github.com/Team7-ProjectWeek/trivia-ninja/pull/84
