### ISSUE TITLE
No indication of progress is presented

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#34]
### Steps to reproduce:
 1. Load the home page
 1. Start a quiz with 50 questions
 1. Answer a bunch of questions

### Expected behavior: 
Some indication of what question number I'm on. 

### Actual behavior: 
No indication of what question I'm on.

**Comment by nicuparente** [comment]
Stats for correct answer and current question has been added under PR #27 
![image](https://cloud.githubusercontent.com/assets/7001751/26693515/481d1ff6-46b9-11e7-986b-19c775ef5c4a.png)
