### ISSUE TITLE
No mechanism for pausing the quiz

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#35]
### Steps to reproduce:
 1. Load the home page
 1. Start a 50 question quiz
 1. Answer a bunch of questions

### Expected behavior: 
Click a ⏸ button to let me take a bathroom break or get interrupted by a family member during a long quiz.

### Actual behavior: 
The timer relentlessly counts done, sucking my precious points away.

**Comment by portermichael** [comment]
Issue is intentional in design mimicking a true ninja work environment and reducing tricky google ninja efficiency. Thanks for the feedback!
