### ISSUE TITLE
It's possible to get points without selecting an answer

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#37]
### Steps to reproduce:
 1. Load the home page
 1. Start a quiz with 50 questions
 1. Answer a True/False question correctly (let's say the answer is: True)
 1. If the next question is ALSO a T/F question, with the same answer, the use can click "Next" without selecting a response.
 1. Points are awarded, and the console logs "True === True"

### Expected behavior: 
No points should be given, unless the correct answer is selected. 

### Actual behavior: 
Points are awarded, even though no answer is selected.

**Comment by portermichael** [comment]
User must now select an answer before next button is available.

https://github.com/Team7-ProjectWeek/trivia-ninja/pull/53
