### ISSUE TITLE
There is no 404 page

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#40]
### Steps to reproduce:
 1. Go to an invalid page route, like: https://trivia-ninja.herokuapp.com/game/10/asdf

### Expected behavior: 
As a user, I want a 404 page to indicate the kind of error that occurred, with directions back to safety. 

### Actual behavior: 
<img width="1016" alt="screen shot 2017-05-31 at 11 57 55 pm" src="https://cloud.githubusercontent.com/assets/11095/26668083/fb32e9de-465c-11e7-9417-fecb35a2ff17.png">

**Comment by portermichael** [comment]
Invalid URLs now return user to '/' page. Thanks for the feedback!

https://github.com/Team7-ProjectWeek/trivia-ninja/pull/50/files
