### ISSUE TITLE
Last question doesn't initially display a "done" button

### ISSUE THREAD

**Issue by brookr** [Team7-ProjectWeek/trivia-ninja#41]
### Steps to reproduce:
 1. Start a quiz, like: https://trivia-ninja.herokuapp.com/game/1/medium/

### Expected behavior: 
As a user, I want to not have to click the button twice to complete the quiz, so that extra time penalty is not incurred. 

### Actual behavior: 
Clicking "next" changes the button to "Done", and I have to realize that nothing happened, and click it again.

**Comment by nicuparente** [comment]
This issue has been fixed under PR #22
